# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_view.ui'
#
# Created: Wed Sep 11 17:31:40 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1413, 794)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 300, 571, 451))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.logConsole = QtGui.QTextEdit(self.groupBox)
        self.logConsole.setGeometry(QtCore.QRect(10, 20, 551, 291))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.logConsole.setPalette(palette)
        self.logConsole.setTabChangesFocus(False)
        self.logConsole.setReadOnly(True)
        self.logConsole.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.logConsole.setObjectName(_fromUtf8("logConsole"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 310, 551, 81))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.clearLogAction = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.clearLogAction.setObjectName(_fromUtf8("clearLogAction"))
        self.horizontalLayout.addWidget(self.clearLogAction)
        self.saveLogAction = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.saveLogAction.setObjectName(_fromUtf8("saveLogAction"))
        self.horizontalLayout.addWidget(self.saveLogAction)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(590, 40, 811, 261))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox_7 = QtGui.QGroupBox(self.tab)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 10, 291, 221))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.ADDRESS_1 = QtGui.QLabel(self.groupBox_7)
        self.ADDRESS_1.setGeometry(QtCore.QRect(20, 20, 261, 16))
        self.ADDRESS_1.setObjectName(_fromUtf8("ADDRESS_1"))
        self.box_k1_a = QtGui.QGroupBox(self.groupBox_7)
        self.box_k1_a.setGeometry(QtCore.QRect(10, 50, 131, 131))
        self.box_k1_a.setObjectName(_fromUtf8("box_k1_a"))
        self.node_k1_a = QtGui.QLabel(self.box_k1_a)
        self.node_k1_a.setGeometry(QtCore.QRect(10, 20, 111, 16))
        self.node_k1_a.setObjectName(_fromUtf8("node_k1_a"))
        self.formLayoutWidget_3 = QtGui.QWidget(self.box_k1_a)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(0, 40, 121, 61))
        self.formLayoutWidget_3.setObjectName(_fromUtf8("formLayoutWidget_3"))
        self.formLayout_3 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setMargin(0)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_12 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_13)
        self.ilim_k1_a = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.ilim_k1_a.setObjectName(_fromUtf8("ilim_k1_a"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.ilim_k1_a)
        self.vlim_k1_a = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.vlim_k1_a.setObjectName(_fromUtf8("vlim_k1_a"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.vlim_k1_a)
        self.box_k1_b = QtGui.QGroupBox(self.groupBox_7)
        self.box_k1_b.setGeometry(QtCore.QRect(149, 50, 131, 131))
        self.box_k1_b.setObjectName(_fromUtf8("box_k1_b"))
        self.node_k1_b = QtGui.QLabel(self.box_k1_b)
        self.node_k1_b.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.node_k1_b.setObjectName(_fromUtf8("node_k1_b"))
        self.formLayoutWidget_4 = QtGui.QWidget(self.box_k1_b)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(0, 40, 121, 61))
        self.formLayoutWidget_4.setObjectName(_fromUtf8("formLayoutWidget_4"))
        self.formLayout_4 = QtGui.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setMargin(0)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_14 = QtGui.QLabel(self.formLayoutWidget_4)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_14)
        self.label_15 = QtGui.QLabel(self.formLayoutWidget_4)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_15)
        self.ilim_k1_b = QtGui.QLineEdit(self.formLayoutWidget_4)
        self.ilim_k1_b.setObjectName(_fromUtf8("ilim_k1_b"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.ilim_k1_b)
        self.vlim_k1_b = QtGui.QLineEdit(self.formLayoutWidget_4)
        self.vlim_k1_b.setObjectName(_fromUtf8("vlim_k1_b"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.vlim_k1_b)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.groupBox_7)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(9, 180, 271, 31))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.reset_compliance_1 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.reset_compliance_1.setObjectName(_fromUtf8("reset_compliance_1"))
        self.horizontalLayout_2.addWidget(self.reset_compliance_1)
        self.apply_compliance_1 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.apply_compliance_1.setObjectName(_fromUtf8("apply_compliance_1"))
        self.horizontalLayout_2.addWidget(self.apply_compliance_1)
        self.groupBox_8 = QtGui.QGroupBox(self.tab)
        self.groupBox_8.setGeometry(QtCore.QRect(310, 10, 291, 221))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.ADDRESS_2 = QtGui.QLabel(self.groupBox_8)
        self.ADDRESS_2.setGeometry(QtCore.QRect(20, 20, 251, 16))
        self.ADDRESS_2.setObjectName(_fromUtf8("ADDRESS_2"))
        self.box_k2_b = QtGui.QGroupBox(self.groupBox_8)
        self.box_k2_b.setGeometry(QtCore.QRect(149, 50, 131, 131))
        self.box_k2_b.setObjectName(_fromUtf8("box_k2_b"))
        self.node_k2_b = QtGui.QLabel(self.box_k2_b)
        self.node_k2_b.setGeometry(QtCore.QRect(10, 20, 111, 16))
        self.node_k2_b.setObjectName(_fromUtf8("node_k2_b"))
        self.formLayoutWidget_5 = QtGui.QWidget(self.box_k2_b)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(0, 40, 121, 61))
        self.formLayoutWidget_5.setObjectName(_fromUtf8("formLayoutWidget_5"))
        self.formLayout_5 = QtGui.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_5.setMargin(0)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.label_17 = QtGui.QLabel(self.formLayoutWidget_5)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_17)
        self.label_18 = QtGui.QLabel(self.formLayoutWidget_5)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_18)
        self.ilim_k2_b = QtGui.QLineEdit(self.formLayoutWidget_5)
        self.ilim_k2_b.setObjectName(_fromUtf8("ilim_k2_b"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.ilim_k2_b)
        self.vlim_k2_b = QtGui.QLineEdit(self.formLayoutWidget_5)
        self.vlim_k2_b.setObjectName(_fromUtf8("vlim_k2_b"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.vlim_k2_b)
        self.box_k2_a = QtGui.QGroupBox(self.groupBox_8)
        self.box_k2_a.setGeometry(QtCore.QRect(10, 50, 131, 131))
        self.box_k2_a.setObjectName(_fromUtf8("box_k2_a"))
        self.node_k2_a = QtGui.QLabel(self.box_k2_a)
        self.node_k2_a.setGeometry(QtCore.QRect(10, 20, 111, 16))
        self.node_k2_a.setObjectName(_fromUtf8("node_k2_a"))
        self.formLayoutWidget_6 = QtGui.QWidget(self.box_k2_a)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(0, 40, 121, 61))
        self.formLayoutWidget_6.setObjectName(_fromUtf8("formLayoutWidget_6"))
        self.formLayout_6 = QtGui.QFormLayout(self.formLayoutWidget_6)
        self.formLayout_6.setMargin(0)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.label_20 = QtGui.QLabel(self.formLayoutWidget_6)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_20)
        self.label_21 = QtGui.QLabel(self.formLayoutWidget_6)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_21)
        self.ilim_k2_a = QtGui.QLineEdit(self.formLayoutWidget_6)
        self.ilim_k2_a.setObjectName(_fromUtf8("ilim_k2_a"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.ilim_k2_a)
        self.vlim_k2_a = QtGui.QLineEdit(self.formLayoutWidget_6)
        self.vlim_k2_a.setObjectName(_fromUtf8("vlim_k2_a"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.FieldRole, self.vlim_k2_a)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.groupBox_8)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 180, 271, 31))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.reset_compliance_2 = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.reset_compliance_2.setObjectName(_fromUtf8("reset_compliance_2"))
        self.horizontalLayout_3.addWidget(self.reset_compliance_2)
        self.apply_compliance_2 = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.apply_compliance_2.setObjectName(_fromUtf8("apply_compliance_2"))
        self.horizontalLayout_3.addWidget(self.apply_compliance_2)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tftwidget = QtGui.QWidget()
        self.tftwidget.setObjectName(_fromUtf8("tftwidget"))
        self.groupBox_3 = QtGui.QGroupBox(self.tftwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 381, 221))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.formLayoutWidget = QtGui.QWidget(self.groupBox_3)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 211, 131))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.vgstart = QtGui.QLineEdit(self.formLayoutWidget)
        self.vgstart.setText(_fromUtf8(""))
        self.vgstart.setCursorPosition(0)
        self.vgstart.setPlaceholderText(_fromUtf8(""))
        self.vgstart.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.vgstart.setObjectName(_fromUtf8("vgstart"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.vgstart)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.vgend = QtGui.QLineEdit(self.formLayoutWidget)
        self.vgend.setObjectName(_fromUtf8("vgend"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.vgend)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.vds = QtGui.QLineEdit(self.formLayoutWidget)
        self.vds.setObjectName(_fromUtf8("vds"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.vds)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.step = QtGui.QLineEdit(self.formLayoutWidget)
        self.step.setObjectName(_fromUtf8("step"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.step)
        self.boolFWBW = QtGui.QCheckBox(self.formLayoutWidget)
        self.boolFWBW.setChecked(False)
        self.boolFWBW.setObjectName(_fromUtf8("boolFWBW"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.boolFWBW)
        self.resetTFT = QtGui.QPushButton(self.groupBox_3)
        self.resetTFT.setGeometry(QtCore.QRect(230, 50, 99, 23))
        self.resetTFT.setObjectName(_fromUtf8("resetTFT"))
        self.runTFT = QtGui.QPushButton(self.groupBox_3)
        self.runTFT.setGeometry(QtCore.QRect(230, 20, 99, 23))
        self.runTFT.setObjectName(_fromUtf8("runTFT"))
        self.groupBox_6 = QtGui.QGroupBox(self.tftwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(410, 10, 391, 221))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.formLayoutWidget_7 = QtGui.QWidget(self.groupBox_6)
        self.formLayoutWidget_7.setGeometry(QtCore.QRect(10, 20, 301, 161))
        self.formLayoutWidget_7.setObjectName(_fromUtf8("formLayoutWidget_7"))
        self.formLayout_7 = QtGui.QFormLayout(self.formLayoutWidget_7)
        self.formLayout_7.setMargin(0)
        self.formLayout_7.setObjectName(_fromUtf8("formLayout_7"))
        self.oxideCombo = QtGui.QComboBox(self.formLayoutWidget_7)
        self.oxideCombo.setObjectName(_fromUtf8("oxideCombo"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.FieldRole, self.oxideCombo)
        self.label_7 = QtGui.QLabel(self.formLayoutWidget_7)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.label_9 = QtGui.QLabel(self.formLayoutWidget_7)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_9)
        self.tft_eps_r = QtGui.QLineEdit(self.formLayoutWidget_7)
        self.tft_eps_r.setObjectName(_fromUtf8("tft_eps_r"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.FieldRole, self.tft_eps_r)
        self.tft_t_ox = QtGui.QLineEdit(self.formLayoutWidget_7)
        self.tft_t_ox.setObjectName(_fromUtf8("tft_t_ox"))
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.FieldRole, self.tft_t_ox)
        self.label_10 = QtGui.QLabel(self.formLayoutWidget_7)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtGui.QLabel(self.formLayoutWidget_7)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_7.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_11)
        self.tft_w = QtGui.QLineEdit(self.formLayoutWidget_7)
        self.tft_w.setObjectName(_fromUtf8("tft_w"))
        self.formLayout_7.setWidget(3, QtGui.QFormLayout.FieldRole, self.tft_w)
        self.tft_l = QtGui.QLineEdit(self.formLayoutWidget_7)
        self.tft_l.setObjectName(_fromUtf8("tft_l"))
        self.formLayout_7.setWidget(4, QtGui.QFormLayout.FieldRole, self.tft_l)
        self.label_16 = QtGui.QLabel(self.formLayoutWidget_7)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_7.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_16)
        self.tftConfigname = QtGui.QLineEdit(self.formLayoutWidget_7)
        self.tftConfigname.setObjectName(_fromUtf8("tftConfigname"))
        self.formLayout_7.setWidget(5, QtGui.QFormLayout.FieldRole, self.tftConfigname)
        self.label_8 = QtGui.QLabel(self.formLayoutWidget_7)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_7.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_8)
        self.actionSaveTFTConfig = QtGui.QPushButton(self.groupBox_6)
        self.actionSaveTFTConfig.setGeometry(QtCore.QRect(240, 180, 75, 23))
        self.actionSaveTFTConfig.setObjectName(_fromUtf8("actionSaveTFTConfig"))
        self.tabWidget.addTab(self.tftwidget, _fromUtf8(""))
        self.bias = QtGui.QWidget()
        self.bias.setObjectName(_fromUtf8("bias"))
        self.groupBox_5 = QtGui.QGroupBox(self.bias)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 10, 781, 211))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.formLayoutWidget_2 = QtGui.QWidget(self.groupBox_5)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 179, 101))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_5 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.samplesPerDecade = QtGui.QSpinBox(self.formLayoutWidget_2)
        self.samplesPerDecade.setObjectName(_fromUtf8("samplesPerDecade"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.samplesPerDecade)
        self.label_6 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.totalTime = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.totalTime.setObjectName(_fromUtf8("totalTime"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.totalTime)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.actionBiasRun = QtGui.QPushButton(self.formLayoutWidget_2)
        self.actionBiasRun.setObjectName(_fromUtf8("actionBiasRun"))
        self.verticalLayout_3.addWidget(self.actionBiasRun)
        self.formLayout_2.setLayout(2, QtGui.QFormLayout.FieldRole, self.verticalLayout_3)
        self.formLayoutWidget_8 = QtGui.QWidget(self.groupBox_5)
        self.formLayoutWidget_8.setGeometry(QtCore.QRect(200, 20, 381, 101))
        self.formLayoutWidget_8.setObjectName(_fromUtf8("formLayoutWidget_8"))
        self.formLayout_8 = QtGui.QFormLayout(self.formLayoutWidget_8)
        self.formLayout_8.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_8.setMargin(0)
        self.formLayout_8.setObjectName(_fromUtf8("formLayout_8"))
        self.label_19 = QtGui.QLabel(self.formLayoutWidget_8)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_19)
        self.currentrun_progress = QtGui.QProgressBar(self.formLayoutWidget_8)
        self.currentrun_progress.setProperty("value", 0)
        self.currentrun_progress.setObjectName(_fromUtf8("currentrun_progress"))
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.FieldRole, self.currentrun_progress)
        self.label_22 = QtGui.QLabel(self.formLayoutWidget_8)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_22)
        self.totaltime_run = QtGui.QProgressBar(self.formLayoutWidget_8)
        self.totaltime_run.setProperty("value", 0)
        self.totaltime_run.setObjectName(_fromUtf8("totaltime_run"))
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.FieldRole, self.totaltime_run)
        self.tabWidget.addTab(self.bias, _fromUtf8(""))
        self.scripts = QtGui.QWidget()
        self.scripts.setObjectName(_fromUtf8("scripts"))
        self.scriptTable = QtGui.QTableWidget(self.scripts)
        self.scriptTable.setGeometry(QtCore.QRect(10, 10, 441, 221))
        self.scriptTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.scriptTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.scriptTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.scriptTable.setColumnCount(3)
        self.scriptTable.setObjectName(_fromUtf8("scriptTable"))
        self.scriptTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.scriptTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.scriptTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.scriptTable.setHorizontalHeaderItem(2, item)
        self.openScript = QtGui.QPushButton(self.scripts)
        self.openScript.setGeometry(QtCore.QRect(470, 10, 111, 23))
        self.openScript.setObjectName(_fromUtf8("openScript"))
        self.loadScriptToDevice = QtGui.QPushButton(self.scripts)
        self.loadScriptToDevice.setGeometry(QtCore.QRect(470, 40, 111, 23))
        self.loadScriptToDevice.setObjectName(_fromUtf8("loadScriptToDevice"))
        self.tabWidget.addTab(self.scripts, _fromUtf8(""))
        self.advancedScripting = QtGui.QWidget()
        self.advancedScripting.setObjectName(_fromUtf8("advancedScripting"))
        self.boolAdvancedScripting = QtGui.QCheckBox(self.advancedScripting)
        self.boolAdvancedScripting.setGeometry(QtCore.QRect(20, 10, 151, 17))
        self.boolAdvancedScripting.setObjectName(_fromUtf8("boolAdvancedScripting"))
        self.scriptEditor = QtGui.QTextEdit(self.advancedScripting)
        self.scriptEditor.setEnabled(False)
        self.scriptEditor.setGeometry(QtCore.QRect(20, 30, 321, 201))
        self.scriptEditor.setObjectName(_fromUtf8("scriptEditor"))
        self.verticalLayoutWidget_5 = QtGui.QWidget(self.advancedScripting)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(360, 30, 111, 54))
        self.verticalLayoutWidget_5.setObjectName(_fromUtf8("verticalLayoutWidget_5"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.openAdvancedScript = QtGui.QPushButton(self.verticalLayoutWidget_5)
        self.openAdvancedScript.setEnabled(False)
        self.openAdvancedScript.setObjectName(_fromUtf8("openAdvancedScript"))
        self.verticalLayout_5.addWidget(self.openAdvancedScript)
        self.uploadAdvancedScript = QtGui.QPushButton(self.verticalLayoutWidget_5)
        self.uploadAdvancedScript.setEnabled(False)
        self.uploadAdvancedScript.setObjectName(_fromUtf8("uploadAdvancedScript"))
        self.verticalLayout_5.addWidget(self.uploadAdvancedScript)
        self.tabWidget.addTab(self.advancedScripting, _fromUtf8(""))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 40, 571, 261))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.deviceTable = QtGui.QTableWidget(self.groupBox_2)
        self.deviceTable.setGeometry(QtCore.QRect(10, 20, 401, 241))
        self.deviceTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.deviceTable.setAlternatingRowColors(True)
        self.deviceTable.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.deviceTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.deviceTable.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.deviceTable.setObjectName(_fromUtf8("deviceTable"))
        self.deviceTable.setColumnCount(4)
        self.deviceTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.deviceTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.deviceTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.deviceTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.deviceTable.setHorizontalHeaderItem(3, item)
        self.deviceTable.horizontalHeader().setCascadingSectionResizes(True)
        self.verticalLayoutWidget = QtGui.QWidget(self.groupBox_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(430, 20, 121, 71))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.actionAddDevice = QtGui.QPushButton(self.verticalLayoutWidget)
        self.actionAddDevice.setObjectName(_fromUtf8("actionAddDevice"))
        self.verticalLayout.addWidget(self.actionAddDevice)
        self.actionRemoveDevice = QtGui.QPushButton(self.verticalLayoutWidget)
        self.actionRemoveDevice.setObjectName(_fromUtf8("actionRemoveDevice"))
        self.verticalLayout.addWidget(self.actionRemoveDevice)
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(590, 300, 811, 451))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.plotWidget = matplotlibWidget(self.groupBox_4)
        self.plotWidget.setGeometry(QtCore.QRect(10, 20, 791, 441))
        self.plotWidget.setObjectName(_fromUtf8("plotWidget"))
        self.database_status_text = QtGui.QLabel(self.centralwidget)
        self.database_status_text.setGeometry(QtCore.QRect(20, 10, 561, 21))
        self.database_status_text.setAutoFillBackground(True)
        self.database_status_text.setStyleSheet(_fromUtf8("font: 75 16pt \"MS Shell Dlg 2\";\n"
""))
        self.database_status_text.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.database_status_text.setObjectName(_fromUtf8("database_status_text"))
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(610, 0, 281, 41))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.actionOpenDatabase = QtGui.QPushButton(self.horizontalLayoutWidget_4)
        self.actionOpenDatabase.setObjectName(_fromUtf8("actionOpenDatabase"))
        self.horizontalLayout_4.addWidget(self.actionOpenDatabase)
        self.actionNewDb = QtGui.QPushButton(self.horizontalLayoutWidget_4)
        self.actionNewDb.setObjectName(_fromUtf8("actionNewDb"))
        self.horizontalLayout_4.addWidget(self.actionNewDb)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1413, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuQuit = QtGui.QMenu(self.menubar)
        self.menuQuit.setObjectName(_fromUtf8("menuQuit"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setPriority(QtGui.QAction.HighPriority)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.menuQuit.addAction(self.actionQuit)
        self.menubar.addAction(self.menuQuit.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "BiasStress", None))
        self.groupBox.setTitle(_translate("MainWindow", "Output", None))
        self.clearLogAction.setText(_translate("MainWindow", "Clear...", None))
        self.saveLogAction.setText(_translate("MainWindow", "Save...", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Keithley 1", None))
        self.ADDRESS_1.setText(_translate("MainWindow", "ADRESS", None))
        self.box_k1_a.setTitle(_translate("MainWindow", "Channel A", None))
        self.node_k1_a.setText(_translate("MainWindow", "NODE", None))
        self.label_12.setText(_translate("MainWindow", "  I lim [A]", None))
        self.label_13.setText(_translate("MainWindow", "  V lim [V]", None))
        self.box_k1_b.setTitle(_translate("MainWindow", "Channel B", None))
        self.node_k1_b.setText(_translate("MainWindow", "NODE", None))
        self.label_14.setText(_translate("MainWindow", "  I lim [A]", None))
        self.label_15.setText(_translate("MainWindow", "  V lim [V]", None))
        self.reset_compliance_1.setText(_translate("MainWindow", "Reset defaults ...", None))
        self.apply_compliance_1.setText(_translate("MainWindow", "Apply...", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Keithley 2", None))
        self.ADDRESS_2.setText(_translate("MainWindow", "ADDRESS", None))
        self.box_k2_b.setTitle(_translate("MainWindow", "Channel B", None))
        self.node_k2_b.setText(_translate("MainWindow", "NODE", None))
        self.label_17.setText(_translate("MainWindow", "  I lim [A]", None))
        self.label_18.setText(_translate("MainWindow", "  V lim [V]", None))
        self.box_k2_a.setTitle(_translate("MainWindow", "Channel A", None))
        self.node_k2_a.setText(_translate("MainWindow", "NODE", None))
        self.label_20.setText(_translate("MainWindow", "  I lim [A]", None))
        self.label_21.setText(_translate("MainWindow", "  V lim [V]", None))
        self.reset_compliance_2.setText(_translate("MainWindow", "Reset defaults ...", None))
        self.apply_compliance_2.setText(_translate("MainWindow", "Apply...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "SETTINGS", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Values", None))
        self.label.setText(_translate("MainWindow", "Vg start [V]", None))
        self.label_2.setText(_translate("MainWindow", "Vg end [V]", None))
        self.label_3.setText(_translate("MainWindow", "Vds [V]", None))
        self.label_4.setText(_translate("MainWindow", "Step", None))
        self.boolFWBW.setText(_translate("MainWindow", "Forward + Backward", None))
        self.resetTFT.setText(_translate("MainWindow", "RESET DEFAULTS", None))
        self.runTFT.setText(_translate("MainWindow", "RUN", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Characteristics", None))
        self.label_7.setText(_translate("MainWindow", "    Oxide :                     ", None))
        self.label_9.setText(_translate("MainWindow", "    eps_r :", None))
        self.label_10.setText(_translate("MainWindow", "    t_ox : ", None))
        self.label_11.setText(_translate("MainWindow", "    W :", None))
        self.label_16.setText(_translate("MainWindow", "     L :", None))
        self.tftConfigname.setPlaceholderText(_translate("MainWindow", "enter a unique config name", None))
        self.label_8.setText(_translate("MainWindow", "    Config name :", None))
        self.actionSaveTFTConfig.setText(_translate("MainWindow", "Save config..", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tftwidget), _translate("MainWindow", "TFT", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Values", None))
        self.label_5.setText(_translate("MainWindow", "# samples / decade", None))
        self.label_6.setText(_translate("MainWindow", "total time [s]", None))
        self.actionBiasRun.setText(_translate("MainWindow", "RUN", None))
        self.label_19.setText(_translate("MainWindow", "Current run :", None))
        self.label_22.setText(_translate("MainWindow", "Total time    :", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.bias), _translate("MainWindow", "BIAS", None))
        item = self.scriptTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "NAME", None))
        item = self.scriptTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "PATH", None))
        item = self.scriptTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "SIZE", None))
        self.openScript.setText(_translate("MainWindow", "Open..", None))
        self.loadScriptToDevice.setText(_translate("MainWindow", "Load to device ...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.scripts), _translate("MainWindow", "SCRIPTS", None))
        self.boolAdvancedScripting.setText(_translate("MainWindow", "Enable advanced scripting", None))
        self.openAdvancedScript.setText(_translate("MainWindow", "Open...", None))
        self.uploadAdvancedScript.setText(_translate("MainWindow", "Upload...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.advancedScripting), _translate("MainWindow", "ADVANCED SCRIPTING", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Devices", None))
        item = self.deviceTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "NAME", None))
        item = self.deviceTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "CHANNEL", None))
        item = self.deviceTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "ADRESS", None))
        item = self.deviceTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "NODE", None))
        self.actionAddDevice.setText(_translate("MainWindow", "Add ...", None))
        self.actionRemoveDevice.setText(_translate("MainWindow", "Remove selected ...", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Plot", None))
        self.database_status_text.setText(_translate("MainWindow", "No working database is selected", None))
        self.actionOpenDatabase.setText(_translate("MainWindow", "Open working database", None))
        self.actionNewDb.setText(_translate("MainWindow", "Create new ...", None))
        self.menuQuit.setTitle(_translate("MainWindow", "File...", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))

from matplotlibWidgetFile import matplotlibWidget
