# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_view.ui'
#
# Created: Thu Sep 05 16:00:13 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1205, 685)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 290, 571, 351))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.logConsole = QtGui.QTextEdit(self.groupBox)
        self.logConsole.setGeometry(QtCore.QRect(10, 20, 551, 291))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.logConsole.setPalette(palette)
        self.logConsole.setTabChangesFocus(False)
        self.logConsole.setReadOnly(True)
        self.logConsole.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.logConsole.setObjectName(_fromUtf8("logConsole"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 310, 201, 31))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.clearLogAction = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.clearLogAction.setObjectName(_fromUtf8("clearLogAction"))
        self.horizontalLayout.addWidget(self.clearLogAction)
        self.saveLogAction = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.saveLogAction.setObjectName(_fromUtf8("saveLogAction"))
        self.horizontalLayout.addWidget(self.saveLogAction)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(590, 10, 601, 271))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tftwidget = QtGui.QWidget()
        self.tftwidget.setObjectName(_fromUtf8("tftwidget"))
        self.groupBox_3 = QtGui.QGroupBox(self.tftwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 571, 221))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.formLayoutWidget = QtGui.QWidget(self.groupBox_3)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 181, 191))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.vgstart = QtGui.QLineEdit(self.formLayoutWidget)
        self.vgstart.setText(_fromUtf8(""))
        self.vgstart.setCursorPosition(0)
        self.vgstart.setPlaceholderText(_fromUtf8(""))
        self.vgstart.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.vgstart.setObjectName(_fromUtf8("vgstart"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.vgstart)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.vgend = QtGui.QLineEdit(self.formLayoutWidget)
        self.vgend.setObjectName(_fromUtf8("vgend"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.vgend)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.vds = QtGui.QLineEdit(self.formLayoutWidget)
        self.vds.setObjectName(_fromUtf8("vds"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.vds)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.step = QtGui.QLineEdit(self.formLayoutWidget)
        self.step.setObjectName(_fromUtf8("step"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.step)
        self.boolFWBW = QtGui.QCheckBox(self.formLayoutWidget)
        self.boolFWBW.setChecked(False)
        self.boolFWBW.setObjectName(_fromUtf8("boolFWBW"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.boolFWBW)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(460, 160, 101, 54))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.resetTFT = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.resetTFT.setObjectName(_fromUtf8("resetTFT"))
        self.verticalLayout_2.addWidget(self.resetTFT)
        self.runTFT = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.runTFT.setObjectName(_fromUtf8("runTFT"))
        self.verticalLayout_2.addWidget(self.runTFT)
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(220, 30, 81, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit.setGeometry(QtCore.QRect(310, 30, 151, 20))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.tabWidget.addTab(self.tftwidget, _fromUtf8(""))
        self.bias = QtGui.QWidget()
        self.bias.setObjectName(_fromUtf8("bias"))
        self.groupBox_5 = QtGui.QGroupBox(self.bias)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 10, 571, 211))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.formLayoutWidget_2 = QtGui.QWidget(self.groupBox_5)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 171, 181))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_5 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.samplesPerDecade = QtGui.QSpinBox(self.formLayoutWidget_2)
        self.samplesPerDecade.setObjectName(_fromUtf8("samplesPerDecade"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.samplesPerDecade)
        self.label_6 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.totalTime = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.totalTime.setObjectName(_fromUtf8("totalTime"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.totalTime)
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.groupBox_5)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(459, 160, 101, 31))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.pushButton_2 = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.verticalLayout_3.addWidget(self.pushButton_2)
        self.label_8 = QtGui.QLabel(self.groupBox_5)
        self.label_8.setGeometry(QtCore.QRect(210, 30, 81, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_2.setGeometry(QtCore.QRect(300, 30, 151, 20))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.tabWidget.addTab(self.bias, _fromUtf8(""))
        self.scripts = QtGui.QWidget()
        self.scripts.setObjectName(_fromUtf8("scripts"))
        self.tableView = QtGui.QTableView(self.scripts)
        self.tableView.setGeometry(QtCore.QRect(10, 10, 291, 221))
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.scripts)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(330, 50, 131, 80))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.pushButton_3 = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.verticalLayout_4.addWidget(self.pushButton_3)
        self.pushButton_4 = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.verticalLayout_4.addWidget(self.pushButton_4)
        self.tabWidget.addTab(self.scripts, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 571, 271))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.deviceTable = QtGui.QTableWidget(self.groupBox_2)
        self.deviceTable.setGeometry(QtCore.QRect(10, 20, 401, 241))
        self.deviceTable.setObjectName(_fromUtf8("deviceTable"))
        self.deviceTable.setColumnCount(4)
        self.deviceTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.deviceTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.deviceTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.deviceTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.deviceTable.setHorizontalHeaderItem(3, item)
        self.verticalLayoutWidget = QtGui.QWidget(self.groupBox_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(430, 20, 121, 141))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.selectAllDevices = QtGui.QPushButton(self.verticalLayoutWidget)
        self.selectAllDevices.setObjectName(_fromUtf8("selectAllDevices"))
        self.verticalLayout.addWidget(self.selectAllDevices)
        self.actionAddDevice = QtGui.QPushButton(self.verticalLayoutWidget)
        self.actionAddDevice.setObjectName(_fromUtf8("actionAddDevice"))
        self.verticalLayout.addWidget(self.actionAddDevice)
        self.deselectAllDevices = QtGui.QPushButton(self.verticalLayoutWidget)
        self.deselectAllDevices.setObjectName(_fromUtf8("deselectAllDevices"))
        self.verticalLayout.addWidget(self.deselectAllDevices)
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(590, 290, 601, 351))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1205, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuQuit = QtGui.QMenu(self.menubar)
        self.menuQuit.setObjectName(_fromUtf8("menuQuit"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setPriority(QtGui.QAction.HighPriority)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.menuQuit.addAction(self.actionQuit)
        self.menubar.addAction(self.menuQuit.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "BiasStress", None))
        self.groupBox.setTitle(_translate("MainWindow", "Output", None))
        self.clearLogAction.setText(_translate("MainWindow", "Clear...", None))
        self.saveLogAction.setText(_translate("MainWindow", "Save...", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Values", None))
        self.label.setText(_translate("MainWindow", "Vg start [V]", None))
        self.label_2.setText(_translate("MainWindow", "Vg end [V]", None))
        self.label_3.setText(_translate("MainWindow", "Vds [V]", None))
        self.label_4.setText(_translate("MainWindow", "Step", None))
        self.boolFWBW.setText(_translate("MainWindow", "Forward + Backward", None))
        self.resetTFT.setText(_translate("MainWindow", "RESET DEFAULTS", None))
        self.runTFT.setText(_translate("MainWindow", "RUN", None))
        self.label_7.setText(_translate("MainWindow", "Script selected :$", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tftwidget), _translate("MainWindow", "TFT", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Values", None))
        self.label_5.setText(_translate("MainWindow", "# samples / decade", None))
        self.label_6.setText(_translate("MainWindow", "total time [s]", None))
        self.pushButton_2.setText(_translate("MainWindow", "RUN", None))
        self.label_8.setText(_translate("MainWindow", "Script selected :", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.bias), _translate("MainWindow", "BIAS", None))
        self.pushButton_3.setText(_translate("MainWindow", "Load TFT", None))
        self.pushButton_4.setText(_translate("MainWindow", "Load Bias", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.scripts), _translate("MainWindow", "SCRIPTS", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Page", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Devices", None))
        item = self.deviceTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "NAME", None))
        item = self.deviceTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "CHANNEL", None))
        item = self.deviceTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "ADRESS", None))
        item = self.deviceTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "VOLTAGE", None))
        self.selectAllDevices.setText(_translate("MainWindow", "Select All", None))
        self.actionAddDevice.setText(_translate("MainWindow", "Add device...", None))
        self.deselectAllDevices.setText(_translate("MainWindow", "Deselect All", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Plot", None))
        self.menuQuit.setTitle(_translate("MainWindow", "File...", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))

